travis:
  secure:
    BINSTAR_TOKEN: cuCUqHefE5SgIcaZW7osNcAHVeqiIto4TfMBsp21ZztdmsT3PTpucGRejXfcTHoOQz8Pcgl5j99eXflRwkos+gU64MguGHP988Q81zC+Z9E6WFu5oJq774S9GdwhxcDip1cgnLww2IR883HoCruGCsZcomVkZNaqseo7GEn7lKd9mLsxEQojXbUynFZvRHmYNboz3GFPkdNo1/7/33EiBUcISzK/CS4vVEGXJkUjSkjTadHod9VL8G/YNB9pp3l7n0dyS9KkUlTq+MwIG5IPF2z010oLK/dO1jELSalJJ6eDLAHdU3/YNpVyiU41W+xoewWg5X0XFM5iehGwIVXJb1ibwjLgbDB/yUkUT47ACVfhGVabvRi/gQOXIDX7LuCa3/SXj6q/mtyigdL0mLTCfkfr5K77wErOUkgGqd1yqI8HQ1n5+lWFlBKXDOQjV+42A8/KfOB88YdXcIL1ppk5rWtj/b8qQeWQRZECfaULCmlMHWsUfBh+EhS94mW+8PkoMI+X2oLvgy9zcaATdOPd7Gwgb9l96xhNe+lu4Zm7Fv8/S7hZvXtG2t5iWvZ31Ml+53I8vn3m0H0KYknF6QAQJiCp/OkncQk3KnnQvd9aOpk0aSm99MqkJJ0JXVK62eGHdzqdw2wQ/GGRR/VcP6RiHOcICj6ZTq2S8lChld37chM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
