travis:
  secure:
    BINSTAR_TOKEN: erXttON2Zf+9tp+TgFJ5vFAfH1qijE0TzKzpCjr22FXF8GCXSLJ7iSQL5LmXV+X1u2vTsSfyFUA/zpmi8SxDSxETp/UsydxEnBBiN+VH49sikLwSb6caW6BQ4Tp44dHwRMWQrm/zpPkc9Nd1khDvRNbiNApAARUbEa3uRJ8Op2QdlYBnlioLjyUv1WxtZtuaKRzB9MffJWVgvWcbTySkEgALHaWVXic0Mtmu/eKPO4FcedRQBfNfFoRfCWUJ1Kub6JwsA1Oy4MTpTfc9Ri9y1DrtakPbpqM9la/2J60v0p5VmKqE74qPiGZ0ueBeVtuKinNBstMJeyiBvZrKGCldsHgcX+8Epez9wV++D521vPrbp/ixP6HmhQoWcXdEXgX/SXbWJZk0ZRkxFHZhgl5zrmz5uDba7vjNMB/V8781hvYizGrlVRXdmH3/3IWHJExGJR4D/Yj9jxRUI2MzWQIy73u7Z0RPNCk9BfIWzR/72++4iZIYYHcRBiSnjE8eLMcTV0ROMiRNFFXO69m90pXnCLo01S93R6T/j8IdfuD9ZpUijg87IUrczEU2N3Id0BkGtp0N2j5Snq38K3ktTR7ZRVhgjv7E9MV7Z4t7PWkBhWmbvqhU2/KXeWdzuM+Wdymlwrp04bC0zVWUg5mYcJvPRXZf0BsV2RRCBDA8ifqzgvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
