travis:
  secure:
    BINSTAR_TOKEN: mYyENflahpa4ybKPMQQbPGXjCiqxzzKb0TiaOtOF3c8T1zHPCjLTgWmCYA6zUxQdEAXQGS480tCpbvojhSKkmS0tYFeXd1bxtHMgt3GmpPXlKoi/9xZXTa8htcZEwm3DKzTXcRG5MpI6geTlO6mFsjQe5GbGHEhvkLXnHT0o85EFA23nsj/sIMlR1FpEPUVmM4KDsvC4srTX9cF9CfdPTTMHvdupJJIFwMCWzIES8tVN0c4+zuFmloVBdtTijmbjlNnxSgKXSKTlPqIO0zR7UI0MA8n8anbY9AVwEsZ/FDTNyHf+iL8p8jTq07JdyCfXvuhAU38KoDASQGmxgfOH/ZZiFY0xdtliLbsRJ749u0qmjGOloHnF93ojeZrba/9xYDBWkjKcfK7M/C1Jqv7szw+9ldFJDw63vxyTKQ7aprPn78a5hgkGHF02ndTdVUYvcPNAnz7KSEN7t0retLyN0RDOth+sMXpOjm6dkAnGiQPZFdMDsUCUwssSpWqvVJXP33w3TD9VIpjA1LwWntW/M0JfdoKh5rpziO+COwXU1zljqhj2VmT3lIOEvaHSdVqFYt2BGfLhyMMirEUHkB+lN96zla4IuOqDzGmXTg+Yvc13s0ixKXpFuHhhcUnR339xZHNrXHGxNsoInMnUV4jqk3hkgwTgaAqMS0xQjO/PaDI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
